org.gradle.jvmargs=-Xmx8G

# Project Versions
java_version=25
mixin_version=0.8.4
fabric_loom_version=1.17-SNAPSHOT
mod_dev_gradle_version=2.0.147
mod_publish_plugin_version=2.2.0

# Build Jar
minecraft_version=26.1
maximum_minecraft_version=26.2

neo_form_version=26.1-1

# Mod Information

# Changing the mod_id alone will not change it everywhere. There will have to be some manual edits in each loader files in order to change mod id fully
mod_id=stop_lightning_destruction_of_item

mod_name=Stop Lightning Destruction of Item
mod_version=1.1.1
mod_release_type=Release
mod_base_package=mc.mian.sldoi
mod_authors=MianReplicate
mod_description=A mod dedicated to preventing items from being struck down by lightning
mod_credits=Jeryn99 (Code)
mod_license=GPL-3.0
logo_file=logo.png
repository_url=https://github.com/MianReplicate/Stop-Lightning-Destruction-of-Item
issue_tracker_url=https://github.com/MianReplicate/Stop-Lightning-Destruction-of-Item/issues

# For publishing purposes
curseforge_id=1094754
modrinth_id=5nD2Yl0n

# Common dependencies
mixin_extras_version=0.5.3

# NeoForge dependencies
neo_version=26.1.2.109
neo_version_range=[26,)
neo_loader_version_range=[1,)

# Forge dependencies
forge_version=62.0.9
forge_version_range=[62,)
forge_loader_version_range=[62,)
event_bus_version=7.0.5

# Fabric dependencies
fabric_loader_version=0.19.5