org.gradle.jvmargs=-Xmx8G

# Project Versions
java_version=21
mixin_version=0.8.4
fabric_loom_version=1.10-SNAPSHOT
mod_dev_gradle_version=2.0.80
mod_publish_plugin_version=2.2.0

# Build Jar
minecraft_version=1.21.1
maximum_minecraft_version=1.21.11

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_form_version=1.21.1-20240808.144430

# Mod Information

# Changing the mod_id alone will not change it everywhere. There will have to be some manual edits in each loader files in order to change mod id fully
mod_id=stop_lightning_destruction_of_item

mod_name=Stop Lightning Destruction of Item
mod_version=1.1.1
mod_release_type=Release
mod_base_package=mc.mian.sldoi
mod_authors=MianReplicate
mod_description=A mod dedicated to preventing items from being struck down by lightning
mod_credits=Jeryn99 (Code)
mod_license=GPL-3.0
logo_file=logo.png
repository_url=https://github.com/MianReplicate/Stop-Lightning-Destruction-of-Item
issue_tracker_url=https://github.com/MianReplicate/Stop-Lightning-Destruction-of-Item/issues

# For publishing purposes
curseforge_id=1094754
modrinth_id=5nD2Yl0n

# Common dependencies
mixin_extras_version=0.4.1

# NeoForge dependencies
neo_version=21.1.139
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Forge dependencies
forge_version=52.1.0
forge_version_range=[52,)
forge_loader_version_range=[52,)

# Fabric dependencies
fabric_loader_version=0.16.3